"""Autonomous reasoning engine (ARM/Reasoning evolution — Phase 1).

A reusable, normalized reasoning layer extracted from the Infinity loop. It maps
a normalized system-state snapshot to a recommended next action so decisions are
generated by shared reasoning code rather than service-local branching.

Public API:
- `reason(...)` -> `ReasoningResult` (dedicated reasoning service; Phase 2)
- `evaluate_state(...)` -> `StateSnapshot` (state evaluator)
- `decide(snapshot)` -> `ReasoningResult` (decision engine)
- `apply_strategy_accuracy(...)` (strategy selector; Phase 2)
- `summarize_feedback(...)` (feedback analyzer; Phase 2)
- `StateSnapshot`, `ReasoningResult` (normalized contracts)
"""

from apps.analytics.services.reasoning.autonomous_reasoning_service import reason
from apps.analytics.services.reasoning.decision_engine import decide
from apps.analytics.services.reasoning.feedback_analyzer import summarize_feedback
from apps.analytics.services.reasoning.reasoning_events import (
    REASONING_EVENT_TYPES,
    build_reasoning_records,
    emit_reasoning_records,
)
from apps.analytics.services.reasoning.recommendation import recommend_next_action
from apps.analytics.services.reasoning.state_evaluator import evaluate_state
from apps.analytics.services.reasoning.strategy_selector import apply_strategy_accuracy
from apps.analytics.services.reasoning.types import ReasoningResult, StateSnapshot

__all__ = [
    "reason",
    "evaluate_state",
    "decide",
    "apply_strategy_accuracy",
    "summarize_feedback",
    "build_reasoning_records",
    "emit_reasoning_records",
    "REASONING_EVENT_TYPES",
    "recommend_next_action",
    "StateSnapshot",
    "ReasoningResult",
]
