"""Autonomous reasoning engine (ARM/Reasoning evolution — Phase 1).

A reusable, normalized reasoning layer extracted from the Infinity loop. It maps
a normalized system-state snapshot to a recommended next action so decisions are
generated by shared reasoning code rather than service-local branching.

Public API:
- `evaluate_state(...)` -> `StateSnapshot` (state evaluator)
- `decide(snapshot)` -> `ReasoningResult` (decision engine)
- `StateSnapshot`, `ReasoningResult` (normalized contracts)
"""

from apps.analytics.services.reasoning.decision_engine import decide
from apps.analytics.services.reasoning.state_evaluator import evaluate_state
from apps.analytics.services.reasoning.types import ReasoningResult, StateSnapshot

__all__ = [
    "evaluate_state",
    "decide",
    "StateSnapshot",
    "ReasoningResult",
]
